sudo: false
language: ruby
rvm:
  - 2.3.1
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - bundle
script:
  - bundle exec rake
env:
  matrix:
    - SOLIDUS_BRANCH=v2.5 DB=postgres
    - SOLIDUS_BRANCH=v2.6 DB=postgres
    - SOLIDUS_BRANCH=v2.7 DB=postgres
    - SOLIDUS_BRANCH=v2.8 DB=postgres
    - SOLIDUS_BRANCH=master DB=postgres
    - SOLIDUS_BRANCH=v2.5 DB=mysql
    - SOLIDUS_BRANCH=v2.6 DB=mysql
    - SOLIDUS_BRANCH=v2.7 DB=mysql
    - SOLIDUS_BRANCH=v2.8 DB=mysql
    - SOLIDUS_BRANCH=master DB=mysql
